---
repos:
  - repo: https://github.com/biomejs/pre-commit
    rev: v2.4.8  # Use the sha / tag you want to point at
    hooks:
      - id: biome-check
        files: "\\.(html|jsx?|tsx?|c(js|ts)|m(js|ts)|d\\.(ts|cts|mts)|jsonc?|css|svelte|vue|astro|graphql|gql)$"
